
CREATE TABLE  IF NOT EXISTS USERS(
username VARCHAR(50) NOT NULL UNIQUE ,
PASSWORD VARCHAR(100) NOT NULL ,
 ISLOCKED BOOLEAN DEFAULT FALSE,
 ISENABLED BOOLEAN DEFAULT FALSE,
EMAIL VARCHAR(80) NOT NULL
);


CREATE TABLE IF NOT EXISTS   BANKACCOUNT(
NUMBER VARCHAR(30) NOT NULL UNIQUE,
USERNAME VARCHAR(50),
FOREIGN KEY (USERNAME)
    REFERENCES USERS(USERNAME)
);



CREATE TABLE IF NOT EXISTS  TRANSACTION(
ID BIGINT AUTO_INCREMENT,
SENDER VARCHAR(50) NOT NULL,
RECEIVER VARCHAR(50) NOT NULL,
MONEY NUMERIC NOT NULL,
DATE TIMESTAMP
);



CREATE TABLE IF NOT EXISTS  BANKCARD(
NUMBER VARCHAR(16) NOT NULL,
USERNAME VARCHAR(50),
FOREIGN KEY (USERNAME)
    REFERENCES USERS(USERNAME)
);

CREATE TABLE IF NOT EXISTS  PORTFOLIO(
MONEY NUMERIC  DEFAULT 0,
USERNAME VARCHAR(50),
FOREIGN KEY (USERNAME)
    REFERENCES USERS(USERNAME)
);

CREATE TABLE  IF NOT EXISTS ROLES(
ROLE VARCHAR(30) NOT NULL,
USERNAME VARCHAR(50),
FOREIGN KEY (USERNAME)
    REFERENCES USERS(USERNAME)
);

CREATE TABLE IF NOT EXISTS  TOKEN(
TOKEN VARCHAR(200) NOT NULL,
DATE TIMESTAMP,
EMAIL VARCHAR(80),
FOREIGN KEY (EMAIL)
    REFERENCES USERS(EMAIL)
);
